# Generated by Django 3.1.3 on 2021-02-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0003_auto_20210221_1800'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='questions',
            table=None,
        ),
    ]
