# Generated by Django 3.1.3 on 2021-02-21 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0004_auto_20210221_1802'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='questions',
            table='questions',
        ),
    ]
